// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/bufbuild/connect-go"
	connect2 "github.com/tikfack/server/internal/presentation/connect"
)

// Injectors from favorite_wire.go:

func InitializeFavoriteHandler(opts []connect.HandlerOption) (*connect2.FavoriteServiceServer, error) {
	favoriteUsecase, err := provideFavoriteUsecase()
	if err != nil {
		return nil, err
	}
	favoriteServiceServer := provideFavoriteHandler(favoriteUsecase, opts)
	return favoriteServiceServer, nil
}
