// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/bufbuild/connect-go"
	video "github.com/tikfack/server/internal/application/usecase/video"
	videorepo "github.com/tikfack/server/internal/infrastructure/repository/video"
	connect2 "github.com/tikfack/server/internal/presentation/connect"
)

// Injectors from wire.go:

func InitializeVideoHandler(opts []connect.HandlerOption) (*connect2.VideoServiceServer, error) {
	videoCatalog, err := videorepo.NewVideoRepository()
	if err != nil {
		return nil, err
	}
	videoUsecase := video.NewVideoUsecase(videoCatalog)
	videoServiceServer := provideVideoHandler(videoUsecase, opts)
	return videoServiceServer, nil
}

func InitializeEventLogHandler(opts []connect.HandlerOption) (*connect2.EventLogServiceServer, error) {
	kafkaWriter := provideKafkaWriter()
	eventLogUsecase := provideEventLogUsecase(kafkaWriter)
	eventLogServiceServer := provideEventLogHandler(eventLogUsecase, opts)
	return eventLogServiceServer, nil
}
