// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tikfack/server/internal/application/port (interfaces: VideoCatalog)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_video_repository.go -package=mock github.com/tikfack/server/internal/application/port VideoCatalog
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/tikfack/server/internal/application/model"
	gomock "go.uber.org/mock/gomock"
)

// MockVideoCatalog is a mock of VideoCatalog interface.
type MockVideoCatalog struct {
	ctrl     *gomock.Controller
	recorder *MockVideoCatalogMockRecorder
	isgomock struct{}
}

// MockVideoCatalogMockRecorder is the mock recorder for MockVideoCatalog.
type MockVideoCatalogMockRecorder struct {
	mock *MockVideoCatalog
}

// NewMockVideoCatalog creates a new mock instance.
func NewMockVideoCatalog(ctrl *gomock.Controller) *MockVideoCatalog {
	mock := &MockVideoCatalog{ctrl: ctrl}
	mock.recorder = &MockVideoCatalogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoCatalog) EXPECT() *MockVideoCatalogMockRecorder {
	return m.recorder
}

// GetVideoById mocks base method.
func (m *MockVideoCatalog) GetVideoById(ctx context.Context, dmmId string) (*model.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideoById", ctx, dmmId)
	ret0, _ := ret[0].(*model.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideoById indicates an expected call of GetVideoById.
func (mr *MockVideoCatalogMockRecorder) GetVideoById(ctx, dmmId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideoById", reflect.TypeOf((*MockVideoCatalog)(nil).GetVideoById), ctx, dmmId)
}

// GetVideosByDate mocks base method.
func (m *MockVideoCatalog) GetVideosByDate(ctx context.Context, targetDate time.Time, hits, offset int32) ([]model.Video, *model.SearchMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideosByDate", ctx, targetDate, hits, offset)
	ret0, _ := ret[0].([]model.Video)
	ret1, _ := ret[1].(*model.SearchMetadata)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetVideosByDate indicates an expected call of GetVideosByDate.
func (mr *MockVideoCatalogMockRecorder) GetVideosByDate(ctx, targetDate, hits, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideosByDate", reflect.TypeOf((*MockVideoCatalog)(nil).GetVideosByDate), ctx, targetDate, hits, offset)
}

// GetVideosByID mocks base method.
func (m *MockVideoCatalog) GetVideosByID(ctx context.Context, actressIDs, genreIDs, makerIDs, seriesIDs, directorIDs []string, hits, offset int32, sort, gteDate, lteDate, site, service, floor string) ([]model.Video, *model.SearchMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideosByID", ctx, actressIDs, genreIDs, makerIDs, seriesIDs, directorIDs, hits, offset, sort, gteDate, lteDate, site, service, floor)
	ret0, _ := ret[0].([]model.Video)
	ret1, _ := ret[1].(*model.SearchMetadata)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetVideosByID indicates an expected call of GetVideosByID.
func (mr *MockVideoCatalogMockRecorder) GetVideosByID(ctx, actressIDs, genreIDs, makerIDs, seriesIDs, directorIDs, hits, offset, sort, gteDate, lteDate, site, service, floor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideosByID", reflect.TypeOf((*MockVideoCatalog)(nil).GetVideosByID), ctx, actressIDs, genreIDs, makerIDs, seriesIDs, directorIDs, hits, offset, sort, gteDate, lteDate, site, service, floor)
}

// GetVideosByKeyword mocks base method.
func (m *MockVideoCatalog) GetVideosByKeyword(ctx context.Context, keyword string, hits, offset int32, sort, gteDate, lteDate, site, service, floor string) ([]model.Video, *model.SearchMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideosByKeyword", ctx, keyword, hits, offset, sort, gteDate, lteDate, site, service, floor)
	ret0, _ := ret[0].([]model.Video)
	ret1, _ := ret[1].(*model.SearchMetadata)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetVideosByKeyword indicates an expected call of GetVideosByKeyword.
func (mr *MockVideoCatalogMockRecorder) GetVideosByKeyword(ctx, keyword, hits, offset, sort, gteDate, lteDate, site, service, floor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideosByKeyword", reflect.TypeOf((*MockVideoCatalog)(nil).GetVideosByKeyword), ctx, keyword, hits, offset, sort, gteDate, lteDate, site, service, floor)
}

// SearchVideos mocks base method.
func (m *MockVideoCatalog) SearchVideos(ctx context.Context, keyword, actressID, genreID, makerID, seriesID, directorID string) ([]model.Video, *model.SearchMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchVideos", ctx, keyword, actressID, genreID, makerID, seriesID, directorID)
	ret0, _ := ret[0].([]model.Video)
	ret1, _ := ret[1].(*model.SearchMetadata)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchVideos indicates an expected call of SearchVideos.
func (mr *MockVideoCatalogMockRecorder) SearchVideos(ctx, keyword, actressID, genreID, makerID, seriesID, directorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchVideos", reflect.TypeOf((*MockVideoCatalog)(nil).SearchVideos), ctx, keyword, actressID, genreID, makerID, seriesID, directorID)
}
