sequenceDiagram
    participant Client
    participant Handler as VideoServiceServer
    participant Usecase as VideoUsecase
    participant Repository as VideoRepository
    participant DMMAPI

    Client->>Handler: GetVideosByIDRequest(actress_id[], genre_id[], maker_id[], series_id[], director_id[], hits, offset, sort, gte_date, lte_date, site, service, floor)
    Handler->>Usecase: GetVideosByID(ctx, actress_id[], genre_id[], maker_id[], series_id[], director_id[], hits, offset, sort, gte_date, lte_date, site, service, floor)
    Usecase->>Repository: GetVideosByID(ctx, actress_id[], genre_id[], maker_id[], series_id[], director_id[], hits, offset, sort, gte_date, lte_date, site, service, floor)
    Repository->>DMMAPI: GET /v3/ItemList?actress_id=...&...
    DMMAPI-->>Repository: Response(JSON)
    Repository-->>Usecase: []entity.Video, *entity.SearchMetadata
    Usecase-->>Handler: []entity.Video, *entity.SearchMetadata
    Handler-->>Client: GetVideosByIDResponse(videos, metadata)